import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar";
import SessionProviderComp from "@/components/SessionProviderComp";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen">
        <main className="flex w-full bg-blue-50 ">
          <SessionProviderComp>
            <SideBar />

            <div className="flex flex-col flex-1">
              <Navbar />
              {children}
            </div>
            <Toaster position="bottom-right" reverseOrder={false} />
          </SessionProviderComp>
        </main>
      </body>
    </html>
  );
}
