import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar";
import SessionProviderComp from "@/components/SessionProviderComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen">
        <main className="flex gap-2 w-full bg-blue-50 p-2">
          <SessionProviderComp>
            <SideBar />

            <div className="flex flex-col flex-1">
              <Navbar />
              {children}
            </div>
          </SessionProviderComp>
        </main>
      </body>
    </html>
  );
}
